on:
  release:
    types: [created, published, edited]
name: Upload Artifact Bundle to Release
env:
  DEVELOPER_DIR: '/Applications/Xcode_16.2.app/Contents/Developer'
jobs:
  release:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build for arm64
        run: swift build --disable-sandbox -c release --arch arm64
      - name: Build for x86_64
        run: swift build --disable-sandbox -c release --arch x86_64
      - uses: giginet/github-action-artifactbundle@main
        id: artifactbundle
        with:
          artifact_name: myexecutable
          version: 1.0.0
      - name: Upload Artifact Bundle to Release
        run: |
          BODY="${{ github.event.release.body }}"
          FILENAME="${{ steps.artifactbundle.outputs.bundle_filename }}"
          BUNDLE_PATH="${{ steps.artifactbundle.outputs.bundle_path }}"
          SHA256="${{ steps.artifactbundle.output.bundle_sha256 }}"
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo $BODY
          gh release upload "$FILENAME" "$BUNDLE_PATH"
          NEW_BODY="${BODY}\n${SHA256}"
          gh release update "$TAG_NAME" --body "$NEW_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
